name: Waka Readme

on:
  workflow_dispatch:
    input:
        name:
          description: "enter your name"
          default: "Joseph Kadjangu"
  # schedule:
  #   Runs at every Friday 12AM UTC
  #   - cron: "0 0 * * 5 *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY  }}
          COMMIT_MESSAGE: Weekly sats
          SHOW_MASKED_TIME: true
